site_name: ANU NAIR
nav:
  - Home: index.md
  - Blog: 
    - blog/index.md
  - Archived Blog: https://tzifra.wordpress.com


theme:
  name: material
  logo: asset/logo.ico
  favicon: asset/logo.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.indexes
  
extra:
  homepage: https://anunair.in

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: true
      post_date_format: long
      archive: true
      post_url_format: "{date}/{slug}"
      authors_file: blog/authors.yml
  - search

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra_css:
  - stylesheets/extra.css